<a href="https://colab.research.google.com/github/aravind-3105/Pytorch/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import libraries**

In [2]:
import torch

In [3]:
a = torch.tensor(4.)
print("Value:",a,"\n Shape:  ",a.shape,"\n Type:  ",a.dtype)

Value: tensor(4.) 
 Shape:   torch.Size([]) 
 Type:   torch.float32


In [4]:
a = torch.tensor([1.,2.,3.,4.])
print("Value:",a,"\n Shape:  ",a.shape,"\n Type:  ",a.dtype)

Value: tensor([1., 2., 3., 4.]) 
 Shape:   torch.Size([4]) 
 Type:   torch.float32


In [5]:
a = torch.tensor([[1,2,3],[3,4,3]])
print("Value:",a,"\n Shape:  ",a.shape,"\n Type:  ",a.dtype)

Value: tensor([[1, 2, 3],
        [3, 4, 3]]) 
 Shape:   torch.Size([2, 3]) 
 Type:   torch.int64


In [6]:
shape = (2,3,2)
randomTensor = torch.rand(shape)
zerosTensor = torch.zeros(shape)
onesTensor = torch.ones(shape)
fixedValTensor = torch.full(shape,23)

print(f"Random Tensor: \n {randomTensor} \n")
print(f"Ones Tensor: \n {onesTensor} \n")
print(f"Zeros Tensor: \n {zerosTensor}\n")
print(f"Same val for all elements Tensor: \n {fixedValTensor}\n")

Random Tensor: 
 tensor([[[0.1512, 0.7002],
         [0.0631, 0.7757],
         [0.5084, 0.2415]],

        [[0.3645, 0.4393],
         [0.7644, 0.0896],
         [0.0972, 0.6704]]]) 

Ones Tensor: 
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

Same val for all elements Tensor: 
 tensor([[[23, 23],
         [23, 23],
         [23, 23]],

        [[23, 23],
         [23, 23],
         [23, 23]]])



In [7]:
print(f"Device tensor is stored on: {a.device}")

Device tensor is stored on: cpu


**Compare with numpy operations**

In [8]:
tensor = torch.ones(4,3)
print("Original Matrix: \n",tensor)
tensor[:,1] = 0
print("Col assigned to zero: \n",tensor)
tensor = torch.ones(4,3)
tensor[1,:] = 0
print("Row assigned to zero: \n",tensor)

Original Matrix: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Col assigned to zero: 
 tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])
Row assigned to zero: 
 tensor([[1., 1., 1.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])


**Concatenate operations**

In [9]:
t1 = torch.ones(4,3)
print(t1)
t2 = torch.ones(4,3)
print(t2)
t3 = torch.cat((t1,t2),1)
print("Add to columns\n",t3)
t4 = torch.cat((t1,t2),0)
print("Add to row\n",t4)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Add to columns
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
Add to row
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


**Multiplication**

In [10]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.mul(tensor) 
 tensor([[1., 1., 1.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 1.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor.matmul(tensor.T) 
 tensor([[3., 0., 3., 3.],
        [0., 0., 0., 0.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 0., 3., 3.],
        [0., 0., 0., 0.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])


In [11]:
print("Original\n")
print(tensor, "\n")

print("After : non in place operation\n")
print(tensor.add(5))
print(tensor, "\n")

print("After: in place operation\n")
tensor.add_(5)
print(tensor)

Original

tensor([[1., 1., 1.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

After : non in place operation

tensor([[6., 6., 6.],
        [5., 5., 5.],
        [6., 6., 6.],
        [6., 6., 6.]])
tensor([[1., 1., 1.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

After: in place operation

tensor([[6., 6., 6.],
        [5., 5., 5.],
        [6., 6., 6.],
        [6., 6., 6.]])


# Tensor Gradients

In [12]:
x = torch.tensor([4.])
print(x)
w = torch.tensor(5.,requires_grad=True)
print(w)
b = torch.tensor(6.,requires_grad=True)
print(b)

tensor([4.])
tensor(5., requires_grad=True)
tensor(6., requires_grad=True)


In [13]:
y = w*x + b # y_val = 4x5 + 6 = 26
print("Y: ",y)
print("w: ",w)
print("X: ",x)
print("b: ",b)

Y:  tensor([26.], grad_fn=<AddBackward0>)
w:  tensor(5., requires_grad=True)
X:  tensor([4.])
b:  tensor(6., requires_grad=True)


In [58]:
y.backward()

In [14]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: None
dy/db: None


dy/dw will be same value as x whie dy/dx will be none and dy/db = 1

**Computational Graph**

We create another tensor ``Q`` from ``a`` and ``b``.

\begin{align}Q = 3a^3 - b^2\end{align}


In [36]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [37]:
Q = 3*a**3 - b**2

In [38]:
external_grad = torch.tensor([1., 1.])
# dL/dQ
Q.backward(gradient=external_grad)

In [42]:
print(a.grad == 9*a**2)
print(b.grad == -2*b)

tensor([True, True])
tensor([True, True])


# GPU Support

In [45]:
print(torch.device)

<class 'torch.device'>


In [46]:
torch.cuda.is_available()

False